# yaml 포맷 버전(docker-compose 1.10 이상부터는 해당 버전을 3으로 설정한다)
version: "3"
services:
  client:
    image: ${CLIENT_IMAGE_NAME}
    expose:
      - "3000"
    labels:
      kompose.image-pull-secret: k8s-ghcr
  backend:
    image: ${BACKEND_IMAGE_NAME}
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_app"
    expose:
      - "5000"
    labels:
      kompose.image-pull-secret: k8s-ghcr
  mysql:
    image: ${MYSQL_IMAGE_NAME}
    # unless-stopped 값 적용 시, pod 생성 시, 아래와 같은 warn 메시지를 반환한다.
    # Restart policy 'unless-stopped' in service mysql is not supported, convert it to 'always'
    restart: always
    ports:
      - "3306:3306"
    environment:
      # 환경 변수를 통해, mysql 의 root 패스워드를 설정한다.
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      # 배포 시, 이전 버전의 컨테이너를 지우더라도 DB 에 저장된 데이터가 지워지지않게해주는 volumes 설정이다.
      # 기본은 컨테이너 삭제 시, 해당 컨테이너에 저장된 데이터까지 지워지게됩니다.

      # docker 에는 /var/lib/* 라는 호스트 파일 시스템이 존재하고, DB 처럼 영구적으로 저장해야할 데이터들은 이곳에 저장할 수 있다.
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    labels:
      kompose.image-pull-secret: k8s-ghcr
  nginx:
    image: ${NGINX_IMAGE_NAME}
    restart: always
    ports:
      - "3001:80"
    labels:
      kompose.service.type: nodeport
      # NodePort 는 30000 ~ 32767 포트로 설정해야한다.
      kompose.service.nodeport.port: 31000
      kompose.image-pull-secret: k8s-ghcr
