# yaml 포맷 버전(docker-compose 1.10 이상부터는 해당 버전을 3으로 설정한다)
version: "3"
services:
  client:
    image: ${CLIENT_IMAGE_NAME}
    expose:
      - "3000"
    labels:
      kompose.image-pull-secret: k8s-ghcr
  backend:
    image: ${BACKEND_IMAGE_NAME}
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_app"
    expose:
      - "5000"
    links:
      - mysql
    depends_on:
      - mysql
    labels:
      kompose.image-pull-secret: k8s-ghcr
  mysql:
    image: ${MYSQL_IMAGE_NAME}
    # unless-stopped 값 적용 시, pod 생성 시, 아래와 같은 warn 메시지를 반환한다.
    # Restart policy 'unless-stopped' in service mysql is not supported, convert it to 'always'
    restart: always
    ports:
      - "3306:3306"
    environment:
      # 환경 변수를 통해, mysql 의 root 패스워드를 설정한다.
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_app"
      # "%" 값은 모든 ip 로 부터 로그인을 허용한다.
      # https://serverfault.com/questions/793058/can-not-access-mysql-docker
      # MYSQL_ROOT_HOST: "%"
    labels:
      kompose.image-pull-secret: k8s-ghcr
  nginx:
    image: ${NGINX_IMAGE_NAME}
    restart: always
    ports:
      - "3001:80"
    labels:
      kompose.service.type: nodeport
      # NodePort 는 30000 ~ 32767 포트로 설정해야한다.
      # NodePort(31000) < service port(3001) < target(pod) port(80)
      # https://bcho.tistory.com/1262
      # https://t1.daumcdn.net/cfile/tistory/99ACBB4F5B288E161A?download
      kompose.service.nodeport.port: 30001
      kompose.image-pull-secret: k8s-ghcr
