# PersistentVolumeClaim
# Creates a PersistentVolumeClaim. Can only be created if there is already a PersistentVolume within the cluster
# kompose 는 PersistentVolume 설정 파일은 자동으로 만들어주지않는다.
# https://kompose.io/conversion/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysql-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/volumes/mysql-data"