apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vol-test
  name: vol-test
spec:
  replicas: 1
  selector:
    matchLabels:
      # labels 에 app:vol-test 가 포함된 pod 를 3개 만들어달라는 선언이다.
      # 만약 없다면, 아래 pod template 사용해서 만든다.(아래 pod template 의 labels 에 app:vol-test 가 포함되어있다)
      app: vol-test
  strategy: {}
  # pod template
  template:
    metadata:
      labels:
        app: vol-test
    spec:
      containers:
        - name: vol-test
          image: nginx
          volumeMounts:
            - name: test-vol
              mountPath: /var/log/nginx
          ports:
            - containerPort: 80
          resources: {}
      volumes:
        - name: test-vol
          persistentVolumeClaim:
            # 파드는 pvc 를 통해, pv 에 물리적인 스토리지를 요청한다.
            claimName: vol-test
      restartPolicy: Always
status: {}