apiVersion: v1
kind: Service
metadata:
  labels:
    app: vol-test
  name: vol-test
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 80
  selector:
    app: vol-test
status:
  loadBalancer: {}