name: Deploy K8S(master, worker nodes)

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [feature/k8s-react-test]

jobs:
  deploy:
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: feature/k8s-react-test
      - name: Run docker containers
        run: |
          # docker project name 이 "/" 문자를 허용하지않아, 해당 문자를 "-" 로 대치시켰다.
          # PROJECT_NAME=$(echo ${{ github.repository }} | sed 's/\//-/g')-prod
          chmod +x scripts/k8s_env_build.sh
          chmod +x scripts/k8s_pkg_cfg.sh
          chmod +x scripts/master_node.sh
          chmod +x scripts/work_nodes.sh

          vagrant up
#  cleanup:
#    needs: [ build, deploy ]
#    name: Clean up
#    runs-on: [ self-hosted ]
#    steps:
#      - name: Clean up docker images
#        run: |
#          # docker-compose.yml 파일에서 사용될 환경 변수들을 설정한다.
#          export CLIENT_IMAGE_NAME=${{ env.CLIENT_IMAGE_NAME }}
#          export BACKEND_IMAGE_NAME=${{ env.BACKEND_IMAGE_NAME }}
#          export MYSQL_IMAGE_NAME=${{ env.MYSQL_IMAGE_NAME }}
#          export NGINX_IMAGE_NAME=${{ env.NGINX_IMAGE_NAME }}
#          # 이전 docker 이미지들을 삭제한다.
#          chmod +x scripts/cleanup.sh
#          sh scripts/cleanup.sh