# This is a basic workflow to help you get started with Actions
name: ci / cd

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [feature/docker-react-test]
#    branches: [ master ]

# ghcr 패키지(docker image) URL
# https://github.com/users/mohwa/packages/container/package/mohwa%2Fdocker-k8s-study

env:
  # https://github.com/docker/compose/issues/3927
  DOCKER_CLIENT_TIMEOUT: 120
  COMPOSE_HTTP_TIMEOUT: 120
  # ghcr: github container registry(개별 docker registry 로도 사용할 수 있다)
  # https://github.com/features/packages
  REGISTRY: ghcr.io
  CLIENT_IMAGE_NAME: ghcr.io/${{ github.repository }}-client
  BACKEND_IMAGE_NAME: ghcr.io/${{ github.repository }}-backend
  MYSQL_IMAGE_NAME: ghcr.io/${{ github.repository }}-mysql
  NGINX_IMAGE_NAME: ghcr.io/${{ github.repository }}-nginx
  CLIENT_CONTAINER_NAME: docker-k8s-study-client
  BACKEND_CONTAINER_NAME: docker-k8s-study-backend
  MYSQL_CONTAINER_NAME: docker-k8s-study-mysql
  NGINX_CONTAINER_NAME: docker-k8s-study-nginx
  VERSION: ${{ github.sha }}
  CLIENT_CONTEXT: ./client
  BACKEND_CONTEXT: ./backend
  MYSQL_CONTEXT: ./mysql
  NGINX_CONTEXT: ./nginx

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: feature/docker-react-test
        # docker buildx: 여러 플랫폼(또는 아키텍쳐)(linux/amd64, linux/arm64, linux/ppc64le, linux/s390x, linux/386 등)으로 빌드하는 기능 등을 포함한 CLI 확장 플러그인이다.
        # https://meetup.toast.com/posts/255
        # https://github.com/docker/setup-buildx-action
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        # https://github.com/features/packages
        # 가격 정책
        # https://github.com/features/packages#pricing
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          # 생성한 repository secrets 값을 정의한다.
          password: ${{ secrets.GHP_REACT_TEST }}
      - name: Client build and push
        uses: docker/build-push-action@v2
        id: client_service_build
        with:
          context: ${{ env.CLIENT_CONTEXT }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # ghcr 에 저장할 tag 이름은 ghcr.io/<OWNER>/<IMAGE-NAME> 형식을 따른다.
          # 저장된 이미지는 github 저장소가 아닌, 사용자나 조직 같은 계정 밑에서 관리된다.
          tags: |
            ${{ env.CLIENT_IMAGE_NAME }}:${{ env.VERSION }}
      - name: Backend build and push
        uses: docker/build-push-action@v2
        id: backend_service_build
        with:
          context: ${{ env.BACKEND_CONTEXT }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # ghcr 에 저장할 tag 이름은 ghcr.io/<OWNER>/<IMAGE-NAME> 형식을 따른다.
          # 저장된 이미지는 github 저장소가 아닌, 사용자나 조직 같은 계정 밑에서 관리된다.
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:${{ env.VERSION }}
      - name: Mysql build and push
        uses: docker/build-push-action@v2
        id: mysql_service_build
        with:
          context: ${{ env.MYSQL_CONTEXT }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # ghcr 에 저장할 tag 이름은 ghcr.io/<OWNER>/<IMAGE-NAME> 형식을 따른다.
          # 저장된 이미지는 github 저장소가 아닌, 사용자나 조직 같은 계정 밑에서 관리된다.
          tags: |
            ${{ env.MYSQL_IMAGE_NAME }}:${{ env.VERSION }}
      - name: Nginx build and push
        uses: docker/build-push-action@v2
        id: nginx_service_build
        with:
          context: ${{ env.NGINX_CONTEXT }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # ghcr 에 저장할 tag 이름은 ghcr.io/<OWNER>/<IMAGE-NAME> 형식을 따른다.
          # 저장된 이미지는 github 저장소가 아닌, 사용자나 조직 같은 계정 밑에서 관리된다.
          tags: |
            ${{ env.NGINX_IMAGE_NAME }}:${{ env.VERSION }}

  deploy:
    needs: [ build ]
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: feature/docker-react-test
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_REACT_TEST }}
      - name: Run docker containers
        run: |
          # docker-compose.yml 에서 사용될 환경 변수들을 설정한다.
          export IMAGE_VERSION=${{ env.VERSION }}
          export CLIENT_CONTAINER_NAME=${{ env.CLIENT_CONTAINER_NAME }}
          export BACKEND_CONTAINER_NAME=${{ env.BACKEND_CONTAINER_NAME }}
          export MYSQL_CONTAINER_NAME=${{ env.MYSQL_CONTAINER_NAME }}
          export NGINX_CONTAINER_NAME=${{ env.NGINX_CONTAINER_NAME }}

          chmod +x scripts/deploy.sh
          sh scripts/deploy.sh

          # workspace root path 로 이동한다.
          docker-compose -f docker-compose.yml up -d

          echo $?

  cleanup:
    needs: [ build, deploy ]
    name: Clean up
    runs-on: [ self-hosted ]
    steps:
      - name: Clean up docker images
        run: |
          # docker-compose.yml 에서 사용될 환경 변수들을 설정한다.
          export IMAGE_VERSION=${{ env.VERSION }}
          export CLIENT_IMAGE_NAME=${{ env.CLIENT_IMAGE_NAME }}
          export BACKEND_IMAGE_NAME=${{ env.BACKEND_IMAGE_NAME }}
          export MYSQL_IMAGE_NAME=${{ env.MYSQL_IMAGE_NAME }}
          export NGINX_IMAGE_NAME=${{ env.NGINX_IMAGE_NAME }}

          # scripts path 에 진입한다.
          cd $GITHUB_WORKSPACE/scripts

          chmod +x cleanup.sh
          sh cleanup.sh
